2024-05-04 11:28:13,305 INFO autoreload 149594 123337223966720 Watching for file changes with StatReloader
2024-05-04 11:28:38,765 WARNING log 149594 123337099441728 Not Found: /images
2024-05-04 11:34:21,876 INFO cli 151100 127940784287744 Starting server at tcp:port=5011:interface=0.0.0.0
2024-05-04 11:34:21,877 INFO server 151100 127940784287744 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2024-05-04 11:34:21,877 INFO server 151100 127940784287744 Configuring endpoint tcp:port=5011:interface=0.0.0.0
2024-05-04 11:34:21,877 INFO server 151100 127940784287744 Listening on TCP address 0.0.0.0:5011
2024-05-04 11:34:29,883 ERROR server 151100 127940784287744 Exception inside application: No route found for path 'images'.
Traceback (most recent call last):
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "/media/dk/Backup/Office/RTSP/webrtc-websocket/dj/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'images'.
